### ISSUE TITLE
AttributeError: module 'custom_components.duofern' has no attribute 'async_setup_entry'

### ISSUE THREAD

**Issue by bertdebondt** [gluap/pyduofern-hacs#3]
FYI: get error below in the HA log. Guess it has something to do with a new attribute which the duofern addon does not supply yet.
addon is still fully functional, so no problems there.

Logger: homeassistant.config_entries
Source: config_entries.py:239
First occurred: 3:51:05 PM (1 occurrences)
Last logged: 3:51:05 PM

Error setting up entry duofern for duofern
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
AttributeError: module 'custom_components.duofern' has no attribute 'async_setup_entry'

I'm currently also using the following Rademacher Sun sensor 3200 00 69 : 
https://cdn-reichelt.de/bilder/web/xxl_ws/R800/DF_SONNENSENSOR.png
any chance these will be included in the duofern addon ? In the FHEM addon these sun events were visible.

thanks in advance,

Bert

**Comment by gluap** [comment]
Hi Bert,

I can also see the error message on my system and will look into it. I believe it must have started with the latest homeassistant upgrade. I hope that they didn't deprecate threaded code, because as of now the asynchronous implementation of pyduofern is still a bit rudimentary.

As for the sun sensor I don't have any of these which makes implementing them really hard. But actually I tried to port most of the code from FHEM so (in case you are a pythonist) you will probably see which code path the sun sensor uses and may be able to get it working yourself). The required steps would be:

- try getting the sensor work with pyduofern
- once that works build "sensor" integration that offers the sun sensors to Homeassistant (these can be very lightweight and the homeassistant documentation is rather extensive on how to implement ones own component).

Cheers,
Paul

**Comment by rakaandro** [comment]
I'm on HASS.IO / HA 2021.2.3 / RPi4 with Duofern (HACS) and there are no longer logs as described above.
(I don't see any and duofern is working) rkr

**Comment by bertdebondt** [comment]
Hi gluap,

You fixed this error with the last updates. Error isn't there anymore. case closed.
