### ISSUE TITLE
v0.5.1 dependency (needs HA Core 2023.3.2)

### ISSUE THREAD

**Issue by bcutter** [gluap/pyduofern-hacs#30]
For which reason is HA Core 2023.3.2 set as minimum version for v0.5.1?

Any dependency/feature only available starting with exactly that version of HA?

Or just a release typo for HACS?

![image](https://user-images.githubusercontent.com/13799156/224970057-56041f82-70f9-4ead-9baf-b22ece32aa27.jpeg)

**Comment by gluap** [comment]
@bcutter I just noticed that I hadn't upped the requirement version for years (Requirement previously was still on 0.99) and since the changes introduced by t-animal in #28 were making use of some "newer" stuff (didn't know how new exactly), I put the version I tested it with as requirement - that's the only version I know it works with.

So the reason is: I tested it with that version, and I was quite sure that the previous version requirement was too old for the code.

**Comment by bcutter** [comment]
OK. So we don't know exactly which HA Core version is technically needed but 2023.3.2 is pretty safe as that's the (only) one it was tested with.

That means it will take a few more weeks until I can test the 0.5.1 beta release and provide feedback as first HA Core needs to get updated. I don't like those dependencies where the desire for one component forces one to update other parts, but that's how HA works right 😀 And probably time for an update after 3 smooth months 💁‍♂️

**Comment by gluap** [comment]
TBH I thought that people installing beta versions would be running the bleeding edge of homeassistant anyhow. I reduced the requirement a little.
